version: '3.3'
 
services:
  api:
    image: node:14
    container_name: api
    working_dir: /app
    ports:
      - '80:80'
    volumes:
      - .:/app
    command: bash -c "npm install && yarn && yarn sequelize db:create || true && yarn sequelize db:migrate && yarn sequelize db:seed:all || true && npm start"
