name: Deploy to VPS

on:
  push:
    branches:
      - master
  release:
    types: [ created ]

env:
  REGISTRY_HOST: registry.kapiwa.com.br
  CONTAINER_NAME: kapi-application
  IMAGE_TAG: latest

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push image to VPS Registry
        id: build-image
        run: |
          # Build a docker container
          echo API_PORT=80$'\n'API_SALT=6ern32t9q785wynt461nja3iy5kbl98zxuk7is6e4zgpjvh0jxtx14n3n5v7efoa$'\n'API_PROD=false$'\n'$'\n'DB_HOST=pg.kapiwa.com.br$'\n'DB_USER=postgres$'\n'DB_PASS=postgres$'\n'DB_NAME=kapi$'\n'$'\n'SMTP_HOST=smtp-relay.sendinblue.com$'\n'SMTP_USER=bism4d@gmail.com$'\n'SMTP_PASS=O867F3BApZYJjqV5$'\n'SMTP_PORT=587$'\n'SMTP_SECURE=false$'\n' > .env
          docker build -t $REGISTRY_HOST/$CONTAINER_NAME:$IMAGE_TAG .
          docker push $REGISTRY_HOST/$CONTAINER_NAME:$IMAGE_TAG
          echo "::set-output name=image::$REGISTRY_HOST/$CONTAINER_NAME:$IMAGE_TAG"
